{
  "name": "parent-project",
  "version": "0.2.0",

  # Well, not yet, but we are getting there ☺
  "description": "Will combine a couple of JSON/YAML files while substituting variables. Can be used for package.json generation",
  "keywords": [
    "json",
    "parent-project",
    "yaml"
  ],

  "license": "Zlib",
  "author": "ooxi <violetland@mail.ru>",

  "homepage": "https://github.com/ooxi/parent-project",
  "bugs": "https://github.com/ooxi/parent-project/issues",
  "repository": {
    "type": "git",
    "url": "https://github.com/ooxi/parent-project.git"
  },

  "bin": {
    "parent-project": "./target/cli.js"
  },

  "dependencies": {
    # Not using `jsonpath' since that package runtime patches esprima as well as not being compatible to webpack
    # targeting node
    "jsonpath-plus": "0.16.*",

    # YAML → JSON
    "@types/js-yaml": "3.9.*",
    "js-yaml": "3.9.*",

    "@types/lodash.assign": "4.2.*",
    "lodash.assign": "4.2.*",

    "@types/lodash.foreach": "4.5.*",
    "lodash.foreach": "4.5.*",

    "@types/lodash.forown": "4.4.*",
    "lodash.forown": "4.4.*",

    "@types/lodash.isequal": "4.5.*",
    "lodash.isequal": "4.5.*"
  },

  "devDependencies": {
    "@types/node": "8.0.*",
    "@types/tape": "4.2.*",
    "tape": "4.8.*",
    "ts-loader": "2.3.*",
    "typescript": "2.4.*",
    "webpack": "3.5.*",
    "webpack-configuration-templates": "0.1.*"
  }
}
